// <auto-generated />
namespace SGAP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SGAP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SGAP));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191332386_SGAP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
